executor: KubernetesExecutor
webserver:
  defaultUser:
    username: admin
    password: hazem
images:
  airflow:
    repository: bitnami/airflow
    tag: latest
    pullPolicy: IfNotPresent
dags:
  gitSync:
    enabled: true
    repo: "https://github.com/hazemfrikhi98/movie-analytics.git"
    branch: "main"            # Branch to sync from
    rev: "HEAD"               # Git revision to checkout
    depth: 1                  # Clone depth (1 for shallow clone)
    subPath: "dags" 

