apiVersion: v1
kind: PersistentVolume
metadata:
  name: files-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/hazem/Documents/Deve/dags"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: files-volume-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
